version: "3"
services:
    php:
        build:
            context: ./docker
            dockerfile: Dockerfile
        container_name: php_container
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        ports:
            - "9000"
            - 5173:5173
        networks:
            - application
        depends_on:
            - mariadb
        restart: unless-stopped
    nginx:
        image: nginx:latest
        container_name: nginx_container
        networks:
            - application
        depends_on:
            - mariadb
        ports:
            - 8080:80
        volumes:
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./:/var/www/html
        links:
            - php
        restart: unless-stopped
    mariadb:
        image: mariadb:latest
        container_name: mariadb_container
        ports:
            - "3306:3306"
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - ./mariadb_data:/var/lib/mysql
        networks:
            - application
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping" ]
        restart: unless-stopped
    maildev:
        image: maildev/maildev
        container_name: maildev_container
        ports:
            - 1080:80
            - 25:25
        networks:
            - application
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin_container
        environment:
            PMA_ARBITRARY: 1
            PMA_HOST: mariadb
            PMA_USER: root
        links:
            - mariadb
        ports:
            - 8091:80
        networks:
            - application
networks:
    application:
        driver: bridge
