name: Continuous integration
on:
  push:
    branches:
      - main
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: install
        run: make init

      - name: test
        run: php artisan test --stop-on-failure

